### ISSUE TITLE
Proyecto 2a: Resultado incorrecto

### ISSUE THREAD

**Issue by pposca** [AaronYllanes/DAW2-M9#3]
Esto:
![image](https://user-images.githubusercontent.com/168123/102519594-fd0fb500-4092-11eb-887a-ae80a5a2544a.png)

Tendría que ser:
![image](https://user-images.githubusercontent.com/168123/102519647-0e58c180-4093-11eb-8b4f-44b8b1ade0f5.png)

**Comment by AaronYllanes** [comment]
Tenia el div del container mal cerrado lo he arreglado y ahora el css se aplica correctamente. Creo que el resultado es el esperado.
